USE [master]
GO

/****** Object:  Database [GNIS]    Script Date: 9/18/2019 10:33:45 PM ******/
CREATE DATABASE [GNIS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GNIS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\GNIS.mdf' , SIZE = 401408KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GNIS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\GNIS_log.ldf' , SIZE = 991232KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GNIS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GNIS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GNIS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GNIS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GNIS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GNIS] SET ARITHABORT OFF 
GO

ALTER DATABASE [GNIS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GNIS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GNIS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GNIS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GNIS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GNIS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GNIS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GNIS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GNIS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GNIS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GNIS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GNIS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GNIS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GNIS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GNIS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GNIS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GNIS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GNIS] SET RECOVERY FULL 
GO

ALTER DATABASE [GNIS] SET  MULTI_USER 
GO

ALTER DATABASE [GNIS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GNIS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GNIS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GNIS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GNIS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GNIS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GNIS] SET  READ_WRITE 
GO


